apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
      - name: logger
        image: "younesious/logger-service:1.0.0"
        env:
          - name: RABBIT_URL
            value: "amqp://guest:guest@rabbitmq"
        ports:
          - containerPort: 8084
          - containerPort: 5001
          - containerPort: 50001

---

apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - protocol: TCP
      port: 8084
      name: web-port
      targetPort: 8084
    - protocol: TCP
      port: 5001
      name: rpc-port
      targetPort: 5001
    - protocol:
      port: 50001
      name: grpc-port
      targetPort: 50001
